Add Kisyuizon-Moji Match
orisano/redash_bq_jp pull request #2
Opened 2018-07-31 02:45 UTC by tatakaba

Add Kisyuizon-Moji Match
\u2460-\u24ea - ① ...
\u3280-\u33ff - ㊀...

2018-07-31 06:56 UTC, orisano requested changes

2018-07-31 06:56 UTC, orisano commented on redash_bq_jp/__init__.py
> +import re
unused import

2018-07-31 06:57 UTC, orisano commented
thank you for your contribution.
almost looks good to me.

2018-08-02 03:24 UTC, tatakaba reviewed
sorry! thank you.

2018-08-02 03:52 UTC, orisano approved these changes

2018-08-02 03:52 UTC, merged